#!/bin/bash

sudo apt update
sudo apt install mariadb-server -y

echo "Menjalankan mysql_secure_installation..."

echo -e "123\nn\nn\ny\ny\ny\ny\n" | sudo mysql_secure_installation


sudo mysql -u root -p"123" <<EOF
CREATE DATABASE capstone;
EOF
