#!/bin/bash

sudo git clone https://github.com/zulfahmidev/capstone_api.git /home/cloudbuild/capstone_api && cd /home/cloudbuild/capstone_api

echo "Mengunduh credentials.json dari Google Cloud Storage..........................."
sudo gsutil cp gs://private-capstone/dev/credentials.json /home/cloudbuild/capstone_api

echo "Mengunduh .env dari Google Cloud Storage............................."
sudo gsutil cp gs://private-capstone/dev.env /home/cloudbuild2/capstone_api

echo "Membuat virtual environment Python......................................"
sudo python3 -m venv venv
. venv/bin/activate

echo "Menginstal dependensi dari requirements.txt..."
sudo pip3 install -r requirements.txt

echo "Menjalankan app.py..."
echo "Menjalankan python3 app.py..."
sudo python3 app.py



cd ..
sudo su cloudbuild
cd /home/cloudbuild/
cd /home/cloudbuild/


sudo su - cloudbuild <<EOF
if [ -d "capstone_api" ]; then
    echo "direckori capstone_api ada ................................"
    cd capstone_api
    git pull origin main
    sudo flask db upgrade
else
    echo "direckori capstone_api belum ada ................................"
    echo "mendownlaod scripts install ................................"
    gsutil cp gs://private-capstone/install.sh .
    sudo chmod +x install.sh
    ./install.sh
fi
EOF


#!/bin/bash

# Cek apakah sudah masuk ke pengguna Cloudbuild
if [[ "$(whoami)" != "cloudbuild" ]]; then
    echo "Belum masuk ke pengguna Cloudbuild. Melakukan perubahan..."

    # Masuk ke pengguna Cloudbuild
    sudo su - cloudbuild <<EOF
    cd ~
    # perintah-perintah di sini

    echo "Sudah masuk ke pengguna Cloudbuild"
EOF
else
    echo "Sudah masuk ke pengguna Cloudbuild"
fi